import test from "node:test";
import assert from "node:assert/strict";
import { computeNextEntityId, hasIdConvention, ENTITY_ID_PREFIXES } from "../../admin/idRecommendationService.js";

function fixture({ current = [], deleted = [] } = {}) {
  return {
    allEntitiesRaw: () => current,
    listAuditTargetIds: () => deleted,
  };
}

test("Section 1: the real per-type prefix map matches the actual canonical dataset conventions (hist-/comm-, full names for the rest)", () => {
  assert.equal(ENTITY_ID_PREFIXES.historicalContext, "hist");
  assert.equal(ENTITY_ID_PREFIXES.community, "comm");
  assert.equal(ENTITY_ID_PREFIXES.belief, "belief");
  assert.equal(ENTITY_ID_PREFIXES.place, "place");
  assert.equal(ENTITY_ID_PREFIXES.structure, "structure");
  assert.equal(ENTITY_ID_PREFIXES.story, "story");
  assert.equal(ENTITY_ID_PREFIXES.music, "music");
  assert.equal(ENTITY_ID_PREFIXES.proverb, "proverb");
  assert.equal(ENTITY_ID_PREFIXES.source, "source");
  assert.equal(hasIdConvention("media"), false, "media ids are already auto-generated at upload time — no suggestion needed");
  assert.equal(hasIdConvention("page"), false, "page ids are already auto-generated by pageService.js — no suggestion needed");
});

test("Section 21: next id on an empty type starts at 0001", () => {
  assert.equal(computeNextEntityId("community", fixture()), "comm-0001");
});

test("Section 21: sequential existing ids recommend exactly one past the max", () => {
  const current = [{ entityType: "community", id: "comm-0001" }, { entityType: "community", id: "comm-0002" }];
  assert.equal(computeNextEntityId("community", fixture({ current })), "comm-0003");
});

test("Section 21: a gap in the numbering is never backfilled", () => {
  const current = [
    { entityType: "community", id: "comm-0001" },
    { entityType: "community", id: "comm-0002" },
    { entityType: "community", id: "comm-0004" },
  ];
  assert.equal(computeNextEntityId("community", fixture({ current })), "comm-0005", "must never recommend comm-0003");
});

test("Section 21: every status counts toward the max — published, draft, inReview, archived all included", () => {
  const current = [
    { entityType: "place", id: "place-0001", status: "published" },
    { entityType: "place", id: "place-0002", status: "draft" },
    { entityType: "place", id: "place-0003", status: "inReview" },
    { entityType: "place", id: "place-0004", status: "archived" },
  ];
  assert.equal(computeNextEntityId("place", fixture({ current })), "place-0005");
});

test("Section 21: a permanently-deleted id (no longer in the entities table, but recorded in audit_log) still counts, so it is never recycled", () => {
  const current = [{ entityType: "belief", id: "belief-0001" }];
  const deleted = ["belief-0007", "structure-0099"]; // structure-0099 must never affect belief's own max
  assert.equal(computeNextEntityId("belief", fixture({ current, deleted })), "belief-0008");
});

test("Section 21: malformed/foreign ids are ignored safely rather than crashing or corrupting the max", () => {
  const current = [
    { entityType: "story", id: "story-0002" },
    { entityType: "story", id: "story-abc" }, // non-numeric suffix
    { entityType: "story", id: "story-0001-old" }, // trailing junk, not anchored
    { entityType: "story", id: "not-even-close" },
    { entityType: "story", id: null },
    { entityType: "story", id: 12345 },
  ];
  assert.equal(computeNextEntityId("story", fixture({ current })), "story-0003");
});

test("Section 21: prefix correctness — one type's ids never influence another type's recommendation, even with a shared numeric suffix", () => {
  const current = [
    { entityType: "music", id: "music-0010" },
    { entityType: "structure", id: "structure-0010" },
  ];
  assert.equal(computeNextEntityId("music", fixture({ current })), "music-0011");
  assert.equal(computeNextEntityId("structure", fixture({ current })), "structure-0011");
});

test("an unconfigured entityType throws a clear error rather than silently returning something", () => {
  assert.throws(() => computeNextEntityId("media", fixture()), /No id convention/);
});
