import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { PRODUCTION_ORIGIN, sitemapUrls, validateReleaseArchive } from "./archive-release.js";

const repositoryRoot = resolve(import.meta.dirname, "..");
const distRoot = resolve(repositoryRoot, "dist");

const archive = JSON.parse(await readFile(resolve(repositoryRoot, "data/archive.json"), "utf8"));
validateReleaseArchive(archive);

// "correctness pass" round, Section 6/7: this file used to also bake every
// public v2 cultural entity's static detail URL into sitemap.xml via
// v2SitemapUrls(collectPublicV2Entities()) — a permanent, build-time
// snapshot. That is exactly wrong once V2_DATA_STORE=sqlite is
// authoritative: archiving a runtime entity that was ALSO present at the
// last build would remove it from /sitemap-runtime.xml (correct) while it
// stayed listed here until the next deploy (stale), so an entity archived
// through Admin could still appear in the sitemap ecosystem via
// /sitemap-index.xml -> /sitemap.xml. Fixed by removing entity URLs from
// this static file entirely — cultural-entity URLs (and CMS pages) now
// come ONLY from backend/v2/render/runtimeSitemap.js's /sitemap-runtime.xml,
// which is live-queried from whichever V2Store is authoritative on every
// request, so it is correct in EVERY mode (sqlite, local, firestore,
// memory), not just sqlite. sitemap.xml now contains only truly static
// system routes: v1 detail/category pages plus the v2/discovery category
// HTML pages, none of which are affected by entity publish/archive/restore.
const urls = [
  ...sitemapUrls(archive),
  `${PRODUCTION_ORIGIN}/pages/communities.html`,
  `${PRODUCTION_ORIGIN}/pages/places.html`,
  `${PRODUCTION_ORIGIN}/pages/map.html`,
  `${PRODUCTION_ORIGIN}/pages/collections.html`,
  `${PRODUCTION_ORIGIN}/pages/search.html`,
  `${PRODUCTION_ORIGIN}/pages/proverbs.html`,
  `${PRODUCTION_ORIGIN}/pages/discover.html`,
];

const uniqueUrls = [...new Set(urls)];
if (uniqueUrls.length !== urls.length) throw new Error("generate-sitemap.js produced a duplicate URL.");

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.js at build time — do not hand-edit.
     Cultural-entity and CMS-page URLs are NOT here; see /sitemap-runtime.xml
     (backend/v2/render/runtimeSitemap.js), referenced together with this
     file by /sitemap-index.xml. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${uniqueUrls.map((url) => `  <url><loc>${url}</loc></url>`).join("\n")}
</urlset>
`;

await writeFile(resolve(distRoot, "sitemap.xml"), xml, "utf8");

console.log(`Generated sitemap.xml with ${uniqueUrls.length} static URLs (${sitemapUrls(archive).length} v1 + 7 v2/discovery category pages). Cultural entities and CMS pages are served live from /sitemap-runtime.xml instead.`);
