import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { PRODUCTION_ORIGIN, sitemapUrls, validateReleaseArchive } from "./archive-release.js";
import { collectPublicV2Entities, v2SitemapUrls } from "./v2-archive-release.js";

const repositoryRoot = resolve(import.meta.dirname, "..");
const distRoot = resolve(repositoryRoot, "dist");

const archive = JSON.parse(await readFile(resolve(repositoryRoot, "data/archive.json"), "utf8"));
validateReleaseArchive(archive);

const v2Entities = await collectPublicV2Entities();

// v1 URLs (home, 6 v1 category pages, methodology, 23 v1 detail pages) +
// the 2 new v2 category pages (communities.html, places.html — beliefs.html
// and structures.html are already covered by sitemapUrls(), since those
// pages kept their v1 URLs even though they now render v2 data) + every
// public v2 entity's static detail page.
const urls = [
  ...sitemapUrls(archive),
  `${PRODUCTION_ORIGIN}/pages/communities.html`,
  `${PRODUCTION_ORIGIN}/pages/places.html`,
  `${PRODUCTION_ORIGIN}/pages/map.html`,
  `${PRODUCTION_ORIGIN}/pages/collections.html`,
  `${PRODUCTION_ORIGIN}/pages/search.html`,
  ...v2SitemapUrls(v2Entities),
];

const uniqueUrls = [...new Set(urls)];
if (uniqueUrls.length !== urls.length) throw new Error("generate-sitemap.js produced a duplicate URL.");

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.js at build time — do not hand-edit. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${uniqueUrls.map((url) => `  <url><loc>${url}</loc></url>`).join("\n")}
</urlset>
`;

await writeFile(resolve(distRoot, "sitemap.xml"), xml, "utf8");

console.log(`Generated sitemap.xml with ${uniqueUrls.length} URLs (${sitemapUrls(archive).length} v1 + 5 v2/discovery category pages + ${v2Entities.length} v2 detail pages).`);
